version: "3.8"

services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_race
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/food_race_unleash"
      DATABASE_SSL: "false"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-token"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "4280:8080"
    profiles:
      - app
    depends_on:
      - postgres
      - unleash
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};
      - Unleash__ApiUrl=http://unleash:4242/api/

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4270:80"
    profiles:
      - app
    depends_on:
      - backend

volumes:
  postgres_data:
